sudo: required
services: 
    - docker

before_install:
    - docker build -t jviddie/perlmanscheduler-test -f ./Dockerfile.dev .
  
script:
    - docker run -e CI=true jviddie/perlmanscheduler-test npm run test

after_success:
    - docker build -t jviddie/perlmanscheduler-client ./client
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push jviddie/perlmanscheduler-client

deploy:
    provider: elasticbeanstalk
    region: "us-west-1"
    app: "perlman-scheduling"
    env: "PerlmanScheduling-env"
    bucket-name: "elasticbeanstalk-us-west-1-869407026545"
    bucket-path: "perlman-scheduling"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
