os:
    - linux

services: 
    - docker

language:
    - ruby

before_install:
    - docker build -t jviddie/perlmanscheduler-test -f ./Dockerfile.dev .
  
script:
    - docker run -e CI=true jviddie/perlmanscheduler-test npm run test

after_success:
    - docker build -t jviddie/perlmanscheduler-client .
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push jviddie/perlmanscheduler-client

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "perlmanscheduler"
    env: "Perlmanscheduler-env"
    bucket: "elasticbeanstalk-us-east-1-995337549165"
    bucket_path: "perlmanscheduler"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
