sudo: required
services: 
    - docker

before_install:
    - docker build -t johnvidmar/docker-react -f Dockerfile.dev .
  
script:
    - docker run johnvidmar/docker-react npm run test -- --coverage
      