sudo: required
services: 
    - docker

before_install:
    - docker build -t johnvidmar/appointments-flow -f Dockerfile.dev .

script:
    - docker run CI=true johnvidmar/appointments-flow npm run test