const PrimaryCareProviders = [

    {
        firstName: 'Carly',
        lastName: 'Babis',
        DEA: 'MB4470198',
        license: 'PA54747',
        NPI:'1679090625',
        ageLimitPrimary: 18,
        ageLimitUrgentCare: 18,
        language: [],
        specialInterests: ['Internal Medicine'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: '',
            suturePlacement: false,
            sutureRemoval: true,
            IUDPlacement: 'Call prior',
            IUDRemoval: 'Call prior',
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/CarlyBabisMain.jpg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/carly-babis-pa-c/',
        inNetwork: true,
        myChart: '270075',
    },
    {
        firstNirstName: 'Puneet',
        LastName: 'Bhalrhu',
        DEA: 'FB6062599',
        license: 'A158762',
        NPI:'1174962898',
        ageLimitPrimary: 0,
        ageLimitUrgentCare: 0,
        language: [],
        specialInterests: ['Family Practice '],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: 'knee',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: 'Call prior',
            IUDRemoval: 'Call prior',
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/PuneetBhalrhu-1024x1024.jpg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/puneet-bhalrhu-md/',
        inNetwork: true,
        myChart: '273037',
    },
    {   
        firstName:'Madalasa',
        lastName: 'Bista',
        DEA: 'FB6406044',
        license: 'A145628',
        NPI:'1174966444',
        ageLimitPrimary: 1,
        ageLimitUrgentCare: 1,
        language: ['Nepali'],
        specialInterests: ['Family Medicine'],
        careExceptions: {
            medicationRefills: 'Hard copy prescriptions only',
            newPTAnnuals: true,
            joint: 'knee',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: true,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/10/DrBista500x500.jpg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/madalasa-bista-m-d/', 
        inNetwork: true,
        myChart: '39702',
    },
    {   
        firstName:'Kelsey',
        lastName: 'Brangoccio',
        DEA: 'MB4574390',
        license: 'PA55679',
        NPI:'1296255477',
        ageLimitPrimary: 3,
        ageLimitUrgentCare: 3,
        language: [],
        specialInterests: ['Preventive Health', 'lifestyle changes'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: 'major joint',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: true,
            IUDRemoval: true,
            nexplanonPlacement: true,
            nexplanonRemoval: true,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/Kelsey500x500-1024x1024.jpg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/kelsey-brangoccio-pa-c/', 
        inNetwork: true,
        myChart: '267386',
    },
    {   
        firstName:'Edward',
        lastName: 'Brantz',
        DEA: 'AB8165195',
        license: 'A31523',
        NPI:'1124096656',
        ageLimitPrimary: 5,
        ageLimitUrgentCare: 5,
        language: ['Spanish'],
        specialInterests: ['Family Medicine'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: false,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/PC_provider2.jpg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/dr-edward-brantz/',
        inNetwork: true,
        myChart: '06405',
    },
    {   
        firstName:'Robert',
        lastName: 'Brunst',
        DEA: 'AB8167226',
        license: 'G36956',
        NPI:'1639257546',
        ageLimitPrimary: 18,
        ageLimitUrgentCare: 18,
        language: ['Spanish', 'Dutch', 'German'],
        specialInterests: ['Internal Medicine'],
        careExceptions: {
            medicationRefills: 'Hard copy presciptions only',
            newPTAnnuals: true,
            joint: 'major joint',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/12/RobertBrunst500x500.jpg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/robert-brunst-m-d/',
        inNetwork: true,
        myChart: '08670',
    },
    {   
        firstName:'William',
        lastName: 'Buchner Jr.',
        DEA: 'FB1709344',
        license: 'A109750',
        NPI:'1356599443',
        ageLimitPrimary: 5,
        ageLimitUrgentCare: 5,
        language: [],
        specialInterests: ['Integrative Medicine'],
        careExceptions: {
            medicationRefills: 'Hard copy prescriptions only',
            newPTAnnuals: false,
            joint: 'any',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/Dr.-Buchner-Main.jpg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/william-buchner-m-d/',
        inNetwork: true,
        myChart: '60830',
    },
    {
        firstName: 'Lauren',
        lastName: 'Campagna',
        DEA: 'MC3708724',
        license: 'PA52878',
        NPI:'1679946040',
        ageLimitPrimary: 18,
        ageLimitUrgentCare: 4,
        language: [],
        specialInterests: ['Family Medicine', 'Aesthetic Medicine'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: false,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/fp_milestone-create-1384638-1.jpg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/lauren-campagna-pa/',
        inNetwork: true,
        myChart: '40112',
    },
    {   
        firstName:'Nicholas',
        lastName: 'Canelo',
        DEA: 'FC7399389',
        license: 'A145725',
        NPI:'1104209048',
        ageLimitPrimary: 1,
        ageLimitUrgentCare: 1,
        language: [],
        specialInterests: ['Family Medicine', 'Integrative Medicine'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: 'major joint',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: true,
            IUDRemoval: true,
            nexplanonPlacement: true,
            nexplanonRemoval: true,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/Canelo500x500-1-1.jpg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/nicholas-canelo-m-d/',
        inNetwork: true,
        myChart: '65521',
    },
    {   
        firstName:'Erinn',
        lastName: 'Case',
        DEA: 'MC2691473',
        license: 'F95009488',
        NPI:'1477802833',
        ageLimitPrimary: 0,
        ageLimitUrgentCare: 0,
        language: [],
        specialInterests: ['Family Medicine'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: 'any',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: true,
            IUDRemoval: true,
            nexplanonPlacement: true,
            nexplanonRemoval: true,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/ErinnCase500x500.jpg',
        title: 'FNP-C',
        src: 'https://perlmanclinic.com/ourteam/erinn-case-fnp-c/',
        inNetwork: true,
        myChart: '270607',
    },
    {   
        firstName:'Stephen',
        lastName: 'Caso',
        DEA: 'MC2300628',
        license: 'PA21365',
        NPI:'1083916985',
        ageLimitPrimary: 12,
        ageLimitUrgentCare: 12,
        language: [],
        specialInterests: ['Family Medicine'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: false,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/PC_provider3.jpg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/stephen-caso-pa/',
        inNetwork: true,
        myChart: '82085',
    },
    {   
        firstName:'Christopher',
        lastName: 'Ceriale',
        DEA: 'MC4490683',
        license: 'PA54651',
        NPI:'1255858221',
        ageLimitPrimary: 18,
        ageLimitUrgentCare: 18,
        language: [],
        specialInterests: ['Adolescent to adult age group', 'reproductive health', 'PREP/ HIV/AIDS specialist'],
        careExceptions: {
            medicationRefills: 'Hard copy prescriptions only',
            newPTAnnuals: true,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: true,
            IUDRemoval: true,
            nexplanonPlacement: true,
            nexplanonRemoval: true,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/09/Chris500x500.jpg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/christopher-ceriale-pa-c/',
        inNetwork: true,
        myChart: '263353',
    },
    {   
        firstName:'Alonso',
        lastName: 'Chan',
        DEA: 'MC3044409',
        license: 'PA23195',
        NPI:'1831525286',
        ageLimitPrimary: 0,
        ageLimitUrgentCare: 0,
        language: ['Spanish'],
        specialInterests: ['Family Medicine', 'Emergency Medicine', 'Womens Health', 'Orthopedics'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: 'majore joint',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: true,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/AlonsoChan.jpg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/alonso-chan-pa-c/',
        inNetwork: true,
        myChart: '84690',
    },
    {   
        firstName:'Alexandra',
        lastName: 'Chatfield',
        DEA: 'MC5455577',
        license: 'PA57107',
        NPI:'1215584628',
        ageLimitPrimary: 0,
        ageLimitUrgentCare: 0,
        language: [],
        specialInterests: ['Internal Medicine'],
        careExceptions: {
            medicationRefills: 'No controlled substances',
            newPTAnnuals: true,
            joint: 'knee',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: true,
            IUDRemoval: true,
            nexplanonPlacement: true,
            nexplanonRemoval: true,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/12/AlexandraChatfield500x500.jpg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/alexandra-chatfield-pa-c/',
        inNetwork: true,
        myChart: '278907',
    },
    {   
        firstName:'Gourab',
        lastName: 'Das',
        DEA: 'MD3201833',
        license: 'PA51621',
        NPI:'1487066965',
        ageLimitPrimary: 18,
        ageLimitUrgentCare: 18,
        language: ['Hindi'],
        specialInterests: ['Internal Medicine '],
        careExceptions: {
            medicationRefills: 'Hard copy prescriptions only',
            newPTAnnuals: true,
            joint: 'knee',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/12/GourabDas500x500.jpg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/gourab-das-pa-c/',
        inNetwork: true,
        myChart: '262694',
    },
    {   
        firstName:'Emily',
        lastName: 'Ence',
        DEA: 'ME3367302',
        license: 'PA52084',
        NPI:'1063784478',
        ageLimitPrimary: 12,
        ageLimitUrgentCare: 12,
        language: [],
        specialInterests: ['Preventive Medicine', 'lifestyle changes'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: true,
            nexplanonPlacement: true,
            nexplanonRemoval: true,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/PC_provider4-300x300.jpg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/emily-ence-pa/',
        inNetwork: true,
        myChart: '84615',
    },
    {   
        firstName:'Neenah',
        lastName: 'Grade',
        DEA: 'MG3939432',
        license: 'PA53586',
        NPI:'1063865061',
        ageLimitPrimary: 0,
        ageLimitUrgentCare: 0,
        language: [],
        specialInterests: ['Family Medicine', 'Emergency Medicine'],
        careExceptions: {
            medicationRefills: 'No controlled substances',
            newPTAnnuals: true,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: '',
        title: 'PA-C',
        src: '',
        inNetwork: true,
        myChart: '270085',
    },
    {   
        firstName:'Julie',
        lastName: 'Hoffman',
        DEA: 'MH3857060',
        license: 'PA55348',
        NPI:'1538534805',
        ageLimitPrimary: 0,
        ageLimitUrgentCare: 0,
        language: [],
        specialInterests: ['Peventative Medicine', 'lifestyle changes', 'patient education'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: false,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: true,
            nexplanonRemoval: true,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/JulieHoffmanPhoto.jpg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/julie-hoffman-pa-c/',
        inNetwork: true,
        myChart: '267633',
    },
    {   
        firstName:'Nicholas',
        lastName: 'Kahl',
        DEA: 'MK2254035',
        license: 'F95006360',
        NPI:'1821306598',
        ageLimitPrimary: 0,
        ageLimitUrgentCare: 0,
        language: [],
        specialInterests: ['Family Medicine'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: 'knee, shoulder',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: true,
            nexplanonPlacement: true,
            nexplanonRemoval: true,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/12/NicholasKahl500x500.jpg',
        title: 'FNP-C',
        src: 'https://perlmanclinic.com/ourteam/nicholas-kahl-fnp-c/',
        inNetwork: true,
        myChart: '98164',
    },
    {   
        firstName:'Stephanie',
        lastName: 'Klein',
        DEA: 'MK4147965',
        license: 'PA53918',
        NPI:'1083151674',
        ageLimitPrimary: 5,
        ageLimitUrgentCare: 5,
        language: [],
        specialInterests: ['Family Medicine', 'HIV/AIDS/PREP', 'Hormone therapy', 'In office surgical procedures'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/StephanieKleinPHOTO-1.jpg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/stephanie-klein-pa-c/',
        inNetwork: true,
        myChart: '257289',
    },
    {   
        firstName:'Natalia',
        lastName: 'Kovaleski',
        DEA: 'MK2971530',
        license: 'PA22994',
        NPI:'1841611324',
        ageLimitPrimary: 18,
        ageLimitUrgentCare: 0,
        language: ['Spanish'],
        specialInterests: ['Internal Medicine', 'chronic care management', 'preventive health'],
        careExceptions: {
            medicationRefills: 'Hard copy prescriptions only',
            newPTAnnuals: true,
            joint: 'major joint',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/11/Natalia500x500.jpg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/natalia-kovaleski-pa-c/',
        inNetwork: true,
        myChart: '278112',
    },
    {   
        firstName:'Ilan',
        lastName: 'Kuperman',
        DEA: 'BK6653136',
        license: 'A87018',
        NPI:'1336178169',
        ageLimitPrimary: 18,
        ageLimitUrgentCare: 18,
        language: ['Spanish'],
        specialInterests: ['Integrative Medicine'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: false,
            joint: '',
            suturePlacement: false,
            sutureRemoval: false,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: ' https://perlmanclinic.com/wp-content/uploads/2019/06/Ilan-Kuperman-Final-500-by-500.jpg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/ilan-kuperman-md/',
        inNetwork: true,
        myChart: '16808',
    },
    {   
        firstName:'Melissa',
        lastName: 'Macy',
        DEA: 'FM3980693',
        license: '20A12830',
        NPI:'1326488719',
        ageLimitPrimary: 5,
        ageLimitUrgentCare: 5,
        language: [],
        specialInterests: ['Osteopathic Manipulation', 'Family Medicine', 'Orthopedics'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: false,
            joint: 'any',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/Dr.Macy500x500.jpg',
        title: 'DO',
        src: 'https://perlmanclinic.com/ourteam/melissa-macy-do/',
        inNetwork: true,
        myChart: '82466',
    },
    {   
        firstName:'Paul',
        lastName: 'Marquis',
        DEA: 'BM1144435',
        license: 'G161976',
        NPI:'1407806151',
        ageLimitPrimary: 0,
        ageLimitUrgentCare: 0,
        language: [],
        specialInterests: ['Family Medicine'],
        careExceptions: {
            medicationRefills: 'Hard copy prescriptions only',
            newPTAnnuals: true,
            joint: 'major joint',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2020/01/Marquis500x500.jpeg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/paul-marquis-m-d/',
        inNetwork: true,
        myChart: '279810',
    },
    {   
        firstName:'ChristyAnne',
        lastName: 'Maxson',
        DEA: 'FM6151295',
        license: 'C51943',
        NPI:'1750897500',
        ageLimitPrimary: 0,
        ageLimitUrgentCare: 0,
        language: [],
        specialInterests: ['Adolescent Care', 'Womens Health', 'Young Families'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: false,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: true,
            IUDRemoval: true,
            nexplanonPlacement: true,
            nexplanonRemoval: true,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/ChristyanneMaxsonPhoto.jpg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/christyanne-maxson-m-d/',
        inNetwork: true,
        myChart: '98016',
    },
    {   
        firstName:'Brenna',
        lastName: 'Memole',
        DEA: 'MM4794372',
        license: 'F95008681',
        NPI:'1437698677',
        ageLimitPrimary: 18,
        ageLimitUrgentCare: 18,
        language: [],
        specialInterests: ['Adult Gerontology', 'lifestyle modifications', 'weightloss', 'nutrition', 'preventive health'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: '',
            suturePlacement: false,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/BrennaMemole.jpg',
        title: 'AGNP',
        src: 'https://perlmanclinic.com/ourteam/brenna-memole-agnp-c/',
        inNetwork: true,
        myChart: '269350',
    },
    {   
        firstName:'Nicole',
        lastName: 'Michael',
        DEA: 'MM5569453',
        license: 'F95011609',
        NPI:'1831759315',
        ageLimitPrimary: 16,
        ageLimitUrgentCare: 16,
        language: [],
        specialInterests: ['Family Medicine', 'Emergency Medicine'],
        careExceptions: {
            medicationRefills: 'Hard copy prescriptions only',
            newPTAnnuals: true,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2020/02/NicoleMichael500x500.jpg',
        title: 'FNP',
        src: 'https://perlmanclinic.com/ourteam/nicole-michael/',
        inNetwork: true,
        myChart: '280127',
    },
    {   
        firstName:'Kristen',
        lastName: 'Mott',
        DEA: 'MM5695208',
        license: 'PA57165',
        NPI:'1790339828',
        ageLimitPrimary: 5,
        ageLimitUrgentCare: 5,
        language: [],
        specialInterests: ['Family Medicine'],
        careExceptions: {
            medicationRefills: 'Hard copy prescriptions only',
            newPTAnnuals: true,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2020/02/KristenMott500x500.jpeg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/kristen-mott-pa-c/',
        inNetwork: true,
        myChart: '282508',
    },
    {   
        firstName:'Seymour',
        lastName: 'Myers',
        DEA: 'AM7746881',
        license: 'G35184',
        NPI:'1083657571',
        ageLimitPrimary: 18,
        ageLimitUrgentCare: 18,
        language: [],
        specialInterests: ['Family Medicine', 'hospice', 'end of life planning'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: false,
            joint: '',
            suturePlacement: false,
            sutureRemoval: false,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/dr-3-perlman-clinic.jpg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/seymour-myers-m-d/',
        inNetwork: true,
        myChart: '05073',
    },
    {   
        firstName:'Brooke',
        lastName: 'Myrberg',
        DEA: 'MM5184267',
        license: 'PA56234',
        NPI:'1295206381',
        ageLimitPrimary: 18,
        ageLimitUrgentCare: 10,
        language: [],
        specialInterests: ['Family Medicine'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: true,
            nexplanonRemoval: true,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/BrookeMyrberg500x500.jpg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/brooke-myrberg-pa-c/',
        inNetwork: true,
        myChart: '271056',
    },
    {   
        firstName:'Kenneth',
        lastName: 'Ortiz',
        DEA: 'FO7664635',
        license: 'A156607',
        NPI:'1356761571',
        ageLimitPrimary: 0,
        ageLimitUrgentCare: 0,
        language: ['Pidgin'],
        specialInterests: ['Aesthetic Medicine', 'Geriatrics', 'PREP', 'IUD', 'nexplanon'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: 'major joint',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: true,
            IUDRemoval: true,
            nexplanonPlacement: true,
            nexplanonRemoval: true,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/KennethOrtizMD.jpg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/kenneth-ortiz-m-d/',
        inNetwork: true,
        myChart: '270059',
    },
    {   
        firstName: 'Emilia',
        lastName: 'Parrott',
        DEA: 'FS4640214',
        license: '20A16409',
        NPI:'1114272473',
        ageLimitPrimary: 0,
        ageLimitUrgentCare: 0,
        language: ['Polish'],
        specialInterests: ['Family Medicine', 'HIV/AIDS'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: 'any',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: true,
            IUDRemoval: true,
            nexplanonPlacement: true,
            nexplanonRemoval: true,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/DrParrott.jpg',
        title: 'DO',
        src: 'https://perlmanclinic.com/ourteam/emilia-parrott-do/',
        inNetwork: true,
        myChart: '270103',
    },
    {   
        firstName:'Monica',
        lastName: 'Perlman',
        DEA: 'BP2530447',
        license: 'G70356',
        NPI:'1780796235',
        ageLimitPrimary: 13,
        ageLimitUrgentCare: 13,
        language: ['Spanish'],
        specialInterests: ['Internal Medicine', 'Preventive Medicine', 'Aestheic Medicine'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/PC_provider9.jpg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/dr-monica-perlman/',
        inNetwork: true,
        myChart: '08899',
    },
    {   
        firstName:'Jennifer',
        lastName: 'Phan',
        DEA: 'MP4780789',
        license: 'F95008319',
        NPI:'1609372150',
        ageLimitPrimary: 18,
        ageLimitUrgentCare: 18,
        language: ['Vietnamese', 'Spanish'],
        specialInterests: ['Internal Medicine', 'Emergency Medicine'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/09/JenniferP500x500.jpg',
        title: 'FNP',
        src: 'https://perlmanclinic.com/ourteam/jennifer-phan-fnp-c/',
        inNetwork: true,
        myChart: '34455',
    },
    {   
        firstName:'Sarah',
        lastName: 'Pierce',
        DEA: 'MP4817687',
        license: 'F95008449',
        NPI:'1518455179',
        ageLimitPrimary: 0,
        ageLimitUrgentCare: 0,
        language: [],
        specialInterests: ['Preventive Medicine'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: '',
            suturePlacement: false,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/Sarah-Pierce.jpg',
        title: 'FNP',
        src: 'https://perlmanclinic.com/ourteam/sarah-pierce-fnp-c/',
        inNetwork: true,
        myChart: '35697',
    },
    {   
        firstName:'William',
        lastName: 'Pitt',
        DEA: 'AP5089861',
        license: 'A23081',
        NPI:'1861544850',
        ageLimitPrimary: 18,
        ageLimitUrgentCare: 18,
        language: [],
        specialInterests: ['Interventional Cardiology', 'Internal Medicine'],
        careExceptions: {
            medicationRefills: 'Hard copy prescriptions only',
            newPTAnnuals: true,
            joint: 'major joint',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2020/01/Raheem500x500.jpeg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/mirza-raheem-m-d/',
        inNetwork: true,
        myChart: '01975',
    },
    {   
        firstName:'Mirza',
        lastName: 'Raheem',
        DEA: 'AR7353042',
        license: 'C140215',
        NPI:'1609886647',
        ageLimitPrimary: 16,
        ageLimitUrgentCare: 16,
        language: [],
        specialInterests: ['Internal Medicine'],
        careExceptions: {
            medicationRefills: 'Hard copy prescriptions only',
            newPTAnnuals: true,
            joint: '',
            suturePlacement: false,
            sutureRemoval: false,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2020/01/Raheem500x500.jpeg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/mirza-raheem-m-d/',
        inNetwork: true,
        myChart: '279880',
    },
    {   
        firstName:'Georgina',
        lastName: 'Rai',
        DEA: 'MR4564705',
        license: 'PA54629',
        NPI:'1467974915',
        ageLimitPrimary: 16,
        ageLimitUrgentCare: 16,
        language: [],
        specialInterests: ['Preventive Medicine', 'Womens Health', 'PREP', 'Patient Education'],
        careExceptions: {
            medicationRefills: 'Hard copy prescriptions only',
            newPTAnnuals: true,
            joint: 'any',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: true,
            IUDRemoval: true,
            nexplanonPlacement: true,
            nexplanonRemoval: true,
        },
        img: '',
        title: 'PA-C',
        src: '',
        inNetwork: true,
        myChart: '263319',
    },
    {   
        firstName:'Philippa',
        lastName: 'Rai',
        DEA: 'MR5563615',
        license: 'PA56698',
        NPI:'1174083836',
        ageLimitPrimary: 10,
        ageLimitUrgentCare: 10,
        language: [],
        specialInterests: ['Preventive Medicine', 'womens health', 'mental health', 'laceration repair', 'in office procedures'],
        careExceptions: {
            medicationRefills: 'Hard copy prescriptions only',
            newPTAnnuals: false,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/Pippa500by500-1024x1024.jpg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/philippa-rai-pa-c/',
        inNetwork: true,
        myChart: '272253',
    },
    {   
        firstName:'Jessica',
        lastName: 'Sarder',
        DEA: 'MS4543092',
        license: 'PA55016',
        NPI:'1083124564',
        ageLimitPrimary: 18,
        ageLimitUrgentCare: 18,
        language: ['Spanish'],
        specialInterests: ['Internal Medicine', 'Emergency Medicine', 'PREP/HIV/AIDS'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/JessicaSarderPhoto.jpg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/jessica-sarder-pa-c/',
        inNetwork: true,
        myChart: '97632',
    },
    {   
        firstName:'Adam',
        lastName: 'Shults',
        DEA: 'MS5450503',
        license: 'PA57151',
        NPI:'1093088205',
        ageLimitPrimary: 1,
        ageLimitUrgentCare: 1,
        language: [],
        specialInterests: ['Family Medicine', 'Emergency Medicine', 'PREP/HIV/AIDS'],
        careExceptions: {
            medicationRefills: 'Hard copy prescriptions only',
            newPTAnnuals: true,
            joint: 'major joint',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/10/Adam500x500.jpg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/adam-shults-pa-c/',
        inNetwork: true,
        myChart: '278020',
    },
    {   
        firstName:'Kelly',
        lastName: 'Snowden',
        DEA: 'MS4993374',
        license: 'PA55980',
        NPI:'1770065252',
        ageLimitPrimary: 0,
        ageLimitUrgentCare: 0,
        language: [],
        specialInterests: ['Preventive Medicine', 'Emergency Medicine'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: true,
            IUDRemoval: true,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/KellySnowden.jpg',
        title: 'PA-C',
        src: 'https://perlmanclinic.com/ourteam/kelly-snowden-pa-c/',
        inNetwork: true,
        myChart: '270097',
    },
    {   
        firstName:'Youstina',
        lastName: 'Soliman',
        DEA: 'FS4807953',
        license: 'C160848',
        NPI:'1497036560',
        ageLimitPrimary: 18,
        ageLimitUrgentCare: 12,
        language: ['Arabic'],
        specialInterests: ['Family Medicine'],
        careExceptions: {
            medicationRefills: 'Hard copy prescriptions only',
            newPTAnnuals: true,
            joint: 'major joint',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: true,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/11/DrSoliman500x500.jpg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/youstina-soliman-m-d/',
        inNetwork: true,
        myChart: '277986',
    },
    {   
        firstName:'Anna',
        lastName: 'Stern',
        DEA: 'BS8969000',
        license: 'A88573',
        NPI:'1184728834',
        ageLimitPrimary: 16,
        ageLimitUrgentCare: 16,
        language: [],
        specialInterests: ['Public Health', 'General Preventative Medicine'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: false,
            joint: '',
            suturePlacement: false,
            sutureRemoval: false,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/annastern-jessica.jpg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/anna-stern-m-d/',
        inNetwork: true,
        myChart: '51404',
    },
    {   
        firstName:'Jamie',
        lastName: 'Switzer',
        DEA: 'BS2681852',
        license: '20A6331',
        NPI:'1972513000',
        ageLimitPrimary: 14,
        ageLimitUrgentCare: 14,
        language: [],
        specialInterests: ['Family Medicine'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: false,
            joint: 'major joint',
            suturePlacement: false,
            sutureRemoval: false,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/PC_provider61.jpg',
        title: 'DO',
        src: 'https://perlmanclinic.com/ourteam/dr-jamie-switzer/',
        inNetwork: true,
        myChart: '14436',
    },
    {   
        firstName:'Susan',
        lastName: 'Taylor',
        DEA: 'AT3224122',
        license: 'G55574',
        NPI:'1205872827',
        ageLimitPrimary: 3,
        ageLimitUrgentCare: 3,
        language: [],
        specialInterests: ['Family Medicine'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: false,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: false,
            IUDRemoval: false,
            nexplanonPlacement: true,
            nexplanonRemoval: true,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/Susan-Taylor-MD-Main-Jessica.jpg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/susan-taylor-m-d/',
        inNetwork: true,
        myChart: '257284',
    },
    {   
        firstName:'Rhodaline',
        lastName: 'Tootell',
        DEA: 'FT0481109',
        license: 'C160215',
        NPI:'1063547867',
        ageLimitPrimary: 0,
        ageLimitUrgentCare: 0,
        language: ['Tagalog'],
        specialInterests: ['Preventive Medicine', 'chronic conditions', 'womens health', 'pediatrics'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: true,
            joint: '',
            suturePlacement: false,
            sutureRemoval: false,
            IUDPlacement: true,
            IUDRemoval: true,
            nexplanonPlacement: false,
            nexplanonRemoval: false,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/RhodalineTootell500x500MAIN.jpg',
        title: 'MD',
        src: 'https://perlmanclinic.com/ourteam/rhodaline-tootell-m-d/',
        inNetwork: true,
        myChart: '272234',
    },
    {   
        firstName:'Yuliya',
        lastName: 'Yartseva',
        DEA: 'MY4678693',
        license: 'F95007558',
        NPI:'1750881843',
        ageLimitPrimary: 16,
        ageLimitUrgentCare: 16,
        language: ['Russian'],
        specialInterests: ['Preventive Medicine', 'Family Medicine'],
        careExceptions: {
            medicationRefills: '',
            newPTAnnuals: false,
            joint: '',
            suturePlacement: true,
            sutureRemoval: true,
            IUDPlacement: true,
            IUDRemoval: true,
            nexplanonPlacement: true,
            nexplanonRemoval: true,
        },
        img: 'https://perlmanclinic.com/wp-content/uploads/2019/06/Yuliya-PA-C-1.jpg',
        title: 'FNP-C',
        src: 'https://perlmanclinic.com/ourteam/yuliya-yartseva-fnp-c/',
        inNetwork: true,
        myChart: '263890',
    }

];

export default PrimaryCareProviders;